### ISSUE TITLE
Template and log-parser.py is missing REQUEST_PER_MINUTE_LIMIT env var.

### ISSUE THREAD

**Issue by attobyte** [awslabs/aws-waf-security-automations#74]
`log-parser.py` lambda function requires the Env variable `REQUEST_PER_MINUTE_LIMIT` to function correctly.

The `LambdaWAFLogParserFunction` within `aws-waf-security-automations.template` is missing the `REQUEST_PER_MINUTE_LIMIT` ENV variable.
```
      Environment:
        Variables:
          OUTPUT_BUCKET: !Ref AccessLogBucket
          IP_SET_ID_BLACKLIST: !If [AlbEndpoint, !GetAtt AlbStack.Outputs.WAFBlacklistSet, !GetAtt CloudFrontStack.Outputs.WAFBlacklistSet]
          IP_SET_ID_AUTO_BLOCK: !If [AlbEndpoint, !GetAtt AlbStack.Outputs.WAFScannersProbesSet, !GetAtt CloudFrontStack.Outputs.WAFScannersProbesSet]
          BLACKLIST_BLOCK_PERIOD: !Ref WAFBlockPeriod
          ERROR_PER_MINUTE_LIMIT: !Ref ErrorThreshold
          SEND_ANONYMOUS_USAGE_DATA: !FindInMap ["Solution", "Data", "SendAnonymousUsageData"]
          UUID: !GetAtt CreateUniqueID.UUID
          LIMIT_IP_ADDRESS_RANGES_PER_IP_MATCH_CONDITION: '10000'
          MAX_AGE_TO_UPDATE: '30'
          REGION: !Ref 'AWS::Region'
          LOG_TYPE: !If [AlbEndpoint, 'alb', 'cloudfront']
          METRIC_NAME_PREFIX: !Join ['', !Split ['-', !Ref 'AWS::StackName']]
          LOG_LEVEL: !FindInMap ["Solution", "Data", "LogLevel"]
          STACK_NAME: !Ref 'AWS::StackName
```

Also the `aws-waf-security-automations.template` is missing a parameter to set the `REQUEST_PER_MINUTE_LIMIT` for the `LambdaWAFLogParserFunction`.
